services:
  my-money-ui:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=https://your-url.com/api
      - NODE_ENV=production
